### ISSUE TITLE
支持多数据库同步吗？

### ISSUE THREAD

**Issue by gitzhanglj** [hellobike/tunnel#12]
我的需求是将pg数据库中的表同步到es中（通过kafka），现在已经传到kafka了，但是看到传过去的信息中没有数据库的信息，才想起来我们在配置文件中只配置了一个数据库，不知道是否支持多数据库呢？如果支持，怎么从kafka中获取到这个信息呢？有哪位大神知道的话，请指点一下我

**Comment by xiaoma20082008** [comment]
一般，一个slot就是一个库的，要使用库，就配置多个slot就好了!
