### ISSUE TITLE
请问是否可以提pull request

### ISSUE THREAD

**Issue by huayuanzzb** [hellobike/tunnel#7]
我们最近也在测试这个工具,    也遇到了[单行配置文件不友好](https://github.com/hellobike/tunnel/issues/5#issuecomment-501950756)和 #6 一样的问题, 我们在自己fork的分支已做了相应的修改. 请问是否可以将这些修改merge进来? 如果可以, 应该怎么做?

**Comment by xiaoma20082008** [comment]
当然接受，非常感谢！

发自我的 iPhone

在 2019年6月17日，下午8:11，recaton <notifications@github.com<mailto:notifications@github.com>> 写道：


我们最近也在测试这个工具, 也遇到了单行配置文件不友好<https://github.com/hellobike/tunnel/issues/5#issuecomment-501950756>和 #6<https://github.com/hellobike/tunnel/issues/6> 一样的问题, 我们在自己fork的分支已做了相应的修改. 请问是否可以将这些修改merge进来? 如果可以, 应该怎么做?

**Comment by xiaoma20082008** [comment]
直接提pr就好了！

发自我的 iPhone

在 2019年6月17日，下午8:11，recaton <notifications@github.com<mailto:notifications@github.com>> 写道：


我们最近也在测试这个工具, 也遇到了单行配置文件不友好<https://github.com/hellobike/tunnel/issues/5#issuecomment-501950756>和 #6<https://github.com/hellobike/tunnel/issues/6> 一样的问题, 我们在自己fork的分支已做了相应的修改. 请问是否可以将这些修改merge进来? 如果可以, 应该怎么做?

**Comment by huayuanzzb** [comment]
好的。这两天我代码整理好后提交pull request。

**Comment by heqian1024** [comment]
您好，整理好能不能先发我一份，我想先测试使用下，比较急，谢谢！我的邮箱：heqian@myhexin.com

**Comment by huayuanzzb** [comment]
@heqian1024 好的，我尽量今天整理好。

**Comment by heqian1024** [comment]
太感谢了

**Comment by huayuanzzb** [comment]
@heqian1024 我提了 #8 修复 #6 提到的问题，改动代码不多，你可以看下。

**Comment by heqian1024** [comment]
好的，谢谢！
